# Generated by Django 4.0 on 2021-12-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgbapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dimmer',
        ),
    ]
