# Generated by Django 4.0 on 2021-12-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgbapi', '0002_delete_dimmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('brigtness', models.IntegerField()),
            ],
        ),
    ]
